
if(tC.getCookie('tc_mode_test')==1){(function(){var tc_testmodescriptexec=document.createElement('script');tc_testmodescriptexec.type='text/javascript';tc_testmodescriptexec.src='//manager.tagcommander.com/utils/test_mode_include.php?id=1&site=39&type=exec&rand='+Math.random()+'&version=48.00';(document.getElementsByTagName('body')[0]||document.getElementsByTagName('head')[0]||document.getElementsByTagName('script')[0].parentNode).appendChild(tc_testmodescriptexec);})();(function(){setTimeout(function(){if(typeof top.tc_count!=='undefined'){top.tc_count++;}else{top.tc_count=1;}var tc_newscript=document.createElement('script');tc_newscript.type='text/javascript';tc_newscript.src='//manager.tagcommander.com/utils/livetest/bookmarklet.php?r='+Math.random()+'&nb='+top.tc_count+'&container=39!1&version=48.00';(document.getElementsByTagName('body')[0]||document.getElementsByTagName('head')[0]||document.getElementsByTagName('script')[0].parentNode).appendChild(tc_newscript);},1000);})();}else{if(tC.dedup.ValidRules('65')){if((tc_vars["page_name"]=='Process commande:Panier (Etape 1)')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('65','Nextperf - Cart (http)','132','39','1');(function(){var tc=document.createElement('script');tc.type='text/javascript';tc.src='http://nxtck.com/act.php?zid='+'29727';(document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(tc,null);})();}}}}
if(tC.dedup.ValidRules('69')){if((tc_vars["template_name"]=='productView')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('69','NextPerf - Product view (http)','133','39','1');(function(){var tc=document.createElement('script');tc.type='text/javascript';tc.src='http://nxtck.com/act.php?zid='+'29726'+';pid=Casto'+tc_pdt_list_pdt1;(document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(tc,null);})();}}}}
if(tC.dedup.ValidRules('7')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('7','Tag Commander - Set permanent cookie','201','39','1');tc_setCookie('tc_from_google','yes','30',"/")}}
if(tC.dedup.ValidRules('11')){if((tc_vars["page_name"]=='Process commande:Panier (Etape 1)')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('11','Master Tag Zanox (basket)','95','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'4FFBBAE226EB7D131732'+" zx_mediaslot";document.body.appendChild(div_1);var zx_products=new Array();var temp_zanox=tc_vars["order_products"];for(var i=0;i<temp_zanox.length;i++){var product=temp_zanox[i];zx_products.push({"identifier":"casto"+product['0'],"amount":product['2'],"currency":'EUR',"quantity":product['6']});}
var _zx=_zx||[];_zx.push({"id":'4FFBBAE226EB7D131732'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__1";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}}
if(tC.dedup.ValidRules('13')){if((tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Lancez vous').toLowerCase())!=-1)){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){if(tc_vars["page_name"]!='Catalogue:Résultats de recherche'){tC.launchTag('13','Master Tag Zanox (category)','94','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'25688CBB2152665A88BF'+" zx_mediaslot";document.body.appendChild(div_1);var zx_category=tC.internalFunctions.tc_function_2(tc_vars["page_name"],'10','250');var _zx=_zx||[];_zx.push({"id":'25688CBB2152665A88BF'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__1";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}}}
if(tC.dedup.ValidRules('15')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('15','Master Tag Zanox (checkout)','96','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'17136DDD4DE1B0CA10E7'+" zx_mediaslot";document.body.appendChild(div_1);var zx_products=new Array();var temp_zanox=tc_vars["order_products"];for(var i=0;i<temp_zanox.length;i++){var product=temp_zanox[i];zx_products.push({"identifier":"casto"+product['0'],"amount":product['3'],"currency":'EUR',"quantity":product['6']});}
var zx_transaction=tc_vars["order_id"];var zx_total_amount=tc_vars["order_amount_tf_without_sf"];var zx_total_currency='EUR';var _zx=_zx||[];_zx.push({"id":'17136DDD4DE1B0CA10E7'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__2";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}
if(tC.dedup.ValidRules('17')){if((tc_vars["template_name"]=='productView')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){if(tc_vars["product_delivery_time"]!='Seulement en Magasin'){tC.launchTag('17','Master Tag Zanox (product)','85','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'24773224395F66A5296D'+" zx_mediaslot";document.body.appendChild(div_1);var zx_identifier="casto"+tc_vars["product_id"];var zx_fn=tc_vars["product_name"];var zx_description=tc_vars["product_name"];var zx_brand=tc_vars["product_vendor"];var zx_category=tc_vars["product_category"];var zx_price=tc_vars["product_unit_price_ati"]+"EUR";var zx_amount=tc_vars["product_unit_price_ati"];var zx_currency="EUR";var zx_url=tc_url;var zx_photo='http://www.castorama.fr'+tc_vars["product_img_url"];var _zx=_zx||[];_zx.push({"id":'24773224395F66A5296D'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__1";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}}}
if(tC.dedup.ValidRules('90')){if((tc_vars["page_name"]=='Home Page')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('90','Master Tag Zanox (homepage)','43','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'77BD2E6220902403C59D'+" zx_mediaslot";document.body.appendChild(div_1);var _zx=_zx||[];_zx.push({"id":'77BD2E6220902403C59D'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__2";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}
if(tC.dedup.ValidRules('92')){if((tc_vars["template_name"]=='search:result')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('92','Master Tag Zanox (search)','43','39','1');var div_1=document.createElement("div");div_1.id="tc_div__1";div_1.className="zx_"+'121AA2412B4442D8823C'+" zx_mediaslot";document.body.appendChild(div_1);var zx_search_query=tc_vars["search_kw"];var zx_search_country='FR';var zx_products=new Array();zx_products.push({"currency":'EUR'});var _zx=_zx||[];_zx.push({"id":'121AA2412B4442D8823C'});(function(d){var s=d.createElement("script");s.async=true;s.src=d.location.protocol+"//api.zanox.com/scripts/zanox.js";s.id="tc_script__2";var a=d.getElementsByTagName("script")[0];if(!window.zanox)a.parentNode.insertBefore(s,a);}(document));}}}
if(tC.dedup.ValidRules('23')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('23','Beezup conversion (expert)','225','39','1');var imageElt1=document.createElement("img");imageElt1.id="tc_img_267_1";imageElt1.src="//tracker.beezup.com/SO?StoreId="+'c4be9dd4-9530-4fdd-9b79-e0759c8fa135'+"&OrderMerchantId="+tc_vars["order_id"]+"&TotalCost="+tc_vars["order_amount_tf_without_sf"]+"&ValidPayement="+'TRUE'+"&ListProductId="+tc_concat_productids+"&ListProductQuantity="+tc_concat_productqts+"&ListProductUnitPrice="+tc_concat_productprcs+"";imageElt1.border="0";document.body.appendChild(imageElt1);}}}
if(tC.dedup.ValidRules('71')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('71','Google Adwords Conversion Tag (https)','42','39','1');var google_conversion_id='1049680926';var google_conversion_language='en';var google_conversion_format="3";var google_conversion_color="ffffff";var google_conversion_label='_UWnCOzerwMQnrjD9AM';var google_conversion_value=tc_vars["order_amount_tf_without_sf"];eval(tC.inclusion_conversion_1);}}}
if(tC.dedup.ValidRules('76')){if((tc_vars["page_name"]=='Process commande:Panier (Etape 1)')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('76','Tedemis - Basket page','165','39','1');eval(tC.inclusion_wsconvuid_min_1);var valeur=0;eval(tC.inclusion_statistique_1);var tc_ws_stat_count=0;var tc_ws_stat=function(){if(typeof stat!=="undefined"){stat('castorama','PV','',tc_concat_productids_Casto,'','PANIER');}
else
{if(tc_ws_stat_count<20){setTimeout('tc_ws_stat()',100);tc_ws_stat_count++;}}};tc_ws_stat();var EA_data=["email",tc_vars["order_email"],"scart","1","scartcumul","0"];var temp_pdts=tc_vars["order_products"];for(var i=0;i<temp_pdts.length;i++)
{var product=temp_pdts[i];EA_data.push("prdref","Casto"+product['0'],"prdamount",product['2'],"prdquantity",product['6'],"prdname",product['1']);}
(function(){var d=document,i='et-ea-js';if(!d.location.protocol.indexOf('http')&&!d.getElementById(i)){var o=d.createElement('script'),a=d.getElementsByTagName('script')[0];o.type='text/javascript';o.id=i;o.async='async';o.defer='defer';o.src='//ea.castorama.fr/ea.js';a.parentNode.insertBefore(o,a);}})();}}}
if(tC.dedup.ValidRules('78')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('78','Tedemis - Checkout page','166','39','1');eval(tC.inclusion_wsconvuid_min_1);var valeur=0;var scriptElt2=document.createElement("script");scriptElt2.id="tc_script__1";scriptElt2.language='javascript';scriptElt2.src='//www.wysistat.com/tedemis/statistique.js';(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt2,null);if(valeur==1){var my_order_var='ACHAT/'+tc_vars["order_amount_tf_without_sf"]+'/';var temp_pdts=tc_vars["order_products"];for(var i=0;i<temp_pdts.length;i++)
{var product=temp_pdts[i];my_order_var+='Casto'+product['0']+'='+product['3']+'='+product['6']+'='+product['7']+'!';}
my_order_var+='/'+tc_vars["order_id"];stat('castorama','PV','',tc_concat_productids_Casto,'',my_order_var);}
var EA_data=["email","+tc_getCookie('Id_retargeting')+","ref",tc_vars["order_id"],"amount",tc_vars["order_amount_tf_without_sf"],"type",'',"payment",''];var temp_pdts=tc_vars["order_products"];for(var i=0;i<temp_pdts.length;i++)
{var product=temp_pdts[i];EA_data.push("prdref","Casto"+product['0'],"prdamount",product['3'],"prdquantity",product['6'],"prdname",product['1']);}
(function(){var d=document,i='et-ea-js';if(!d.location.protocol.indexOf('http')&&!d.getElementById(i)){var o=d.createElement('script'),a=d.getElementsByTagName('script')[0];o.type='text/javascript';o.id=i;o.async='async';o.defer='defer';o.src='//ea.castorama.fr/ea.js';a.parentNode.insertBefore(o,a);}})();}}}
if(tC.dedup.ValidRules('93')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('93','NextPerf - Transaction Tag (decuplicate)','53','39','1');(function(){var tc=document.createElement('script');tc.type='text/javascript';tc.src='https://nxtck.com/act.php?zid='+'29728'+';id='+tc_vars["order_id"]+';mt='+tc_vars["order_amount_ati_without_sf"]+";tvalid="+tc_nextperf_dedup;(document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(tc,null);})();}}}
if(tC.dedup.ValidRules('111')){tC.launchTag('111','Adobe - Correspondances avec le datalayer TC','26','39','1');if(typeof tc_vars["all_filters_used"]!="undefined"&&tc_vars["all_filters_used"]!=""){s_FullFilterTypes=tc_vars["all_filters_used"];}else if(typeof s_FullFilterTypes=="undefined"){s_FullFilterTypes="";}
if(typeof tc_vars["cart_id"]!="undefined"&&tc_vars["cart_id"]!=""){s_cartID=tc_vars["cart_id"];}else if(typeof s_cartID=="undefined"){s_cartID="";}
if(typeof tc_vars["channel_overwrite"]!="undefined"&&tc_vars["channel_overwrite"]!=""){s_channelOverwrite=tc_vars["channel_overwrite"];}else if(typeof s_channelOverwrite=="undefined"){s_channelOverwrite="";}
if(typeof tc_vars["current_store"]!="undefined"&&tc_vars["current_store"]!=""){s_curLoc=tc_vars["current_store"];}else if(typeof s_curLoc=="undefined"){s_curLoc="";}
if(typeof tc_vars["delivery_time"]!="undefined"&&tc_vars["delivery_time"]!=""){s_productDeliveryTime=tc_vars["delivery_time"];}else if(typeof s_productDeliveryTime=="undefined"){s_productDeliveryTime="";}
if(typeof tc_vars["discount_information"]!="undefined"&&tc_vars["discount_information"]!=""){s_discountInformation=tc_vars["discount_information"];}else if(typeof s_discountInformation=="undefined"){s_discountInformation="";}
if(typeof s_channel=="undefined"){s_channel="";}
if(typeof tc_vars["highlited_product"]!="undefined"&&tc_vars["highlited_product"]!=""){s_highlitedProduct=tc_vars["highlited_product"];}else if(typeof s_highlitedProduct=="undefined"){s_highlitedProduct="";}
if(typeof tc_vars["int_proxy_exclusion"]!="undefined"&&tc_vars["int_proxy_exclusion"]!=""){s_xForwardedFor=tc_vars["int_proxy_exclusion"];}else if(typeof s_xForwardedFor=="undefined"){s_xForwardedFor="";}
if(typeof tc_vars["last_filter"]!="undefined"&&tc_vars["last_filter"]!=""){s_LastFilterType=tc_vars["last_filter"];}else if(typeof s_LastFilterType=="undefined"){s_LastFilterType="";}
if(typeof tc_vars["last_filter_value"]!="undefined"&&tc_vars["last_filter_value"]!=""){s_LastFilterValue=tc_vars["last_filter_value"];}else if(typeof s_LastFilterValue=="undefined"){s_LastFilterValue="";}
if(typeof tc_vars["newsletter_optin"]!="undefined"&&tc_vars["newsletter_optin"]!=""){s_newsletterRegistration=tc_vars["newsletter_optin"];}else if(typeof s_newsletterRegistration=="undefined"){s_newsletterRegistration="";}
if(typeof tc_vars["order_id"]!="undefined"&&tc_vars["order_id"]!=""){s_orderID=tc_vars["order_id"];}else if(typeof s_orderID=="undefined"){s_orderID="";}
if(typeof tc_vars["page_error"]!="undefined"&&tc_vars["page_error"]!=""){s_errorMessage=tc_vars["page_error"];}else if(typeof s_errorMessage=="undefined"){s_errorMessage="";}
if(typeof tc_vars["page_name"]!="undefined"&&tc_vars["page_name"]!=""){s_pName=tc_vars["page_name"];}else if(typeof s_pName=="undefined"){s_pName="";}
if(typeof tc_vars["page_name_overwrite"]!="undefined"&&tc_vars["page_name_overwrite"]!=""){s_pNameOverwrite=tc_vars["page_name_overwrite"];}else if(typeof s_pNameOverwrite=="undefined"){s_pNameOverwrite="";}
if(typeof tc_vars["product_list"]!="undefined"&&tc_vars["product_list"]!=""){s_prodList=tc_vars["product_list"];}else if(typeof s_prodList=="undefined"){s_prodList="";}
if(typeof tc_vars["product_price"]!="undefined"&&tc_vars["product_price"]!=""){s_prodPrice=tc_vars["product_price"];}else if(typeof s_prodPrice=="undefined"){s_prodPrice="";}
if(typeof tc_vars["promo_code_added"]!="undefined"&&tc_vars["promo_code_added"]!=""){s_promoCodeAdded=tc_vars["promo_code_added"];}else if(typeof s_promoCodeAdded=="undefined"){s_promoCodeAdded="";}
if(typeof tc_vars["promo_code_amount"]!="undefined"&&tc_vars["promo_code_amount"]!=""){s_promoCodeAmount=tc_vars["promo_code_amount"];}else if(typeof s_promoCodeAmount=="undefined"){s_promoCodeAmount="";}
if(typeof tc_vars["promo_code_used"]!="undefined"&&tc_vars["promo_code_used"]!=""){s_promoCodeUsed=tc_vars["promo_code_used"];}else if(typeof s_promoCodeUsed=="undefined"){s_promoCodeUsed="";}
if(typeof tc_vars["promotion_id"]!="undefined"&&tc_vars["promotion_id"]!=""){s_promotionID=tc_vars["promotion_id"];}else if(typeof s_promotionID=="undefined"){s_promotionID="";}
if(typeof tc_vars["saved_cart_content"]!="undefined"&&tc_vars["saved_cart_content"]!=""){s_savedCartContent=tc_vars["saved_cart_content"];}else if(typeof s_savedCartContent=="undefined"){s_savedCartContent="";}
if(typeof tc_vars["search_result_count"]!="undefined"&&tc_vars["search_result_count"]!=""){s_searchResultCount=tc_vars["search_result_count"];}else if(typeof s_searchResultCount=="undefined"){s_searchResultCount="";}
if(typeof tc_vars["search_string"]!="undefined"&&tc_vars["search_string"]!=""){s_searchString=tc_vars["search_string"];}else if(typeof s_searchString=="undefined"){s_searchString="";}
if(typeof tc_vars["search_type"]!="undefined"&&tc_vars["search_type"]!=""){s_searchType=tc_vars["search_type"];}else if(typeof s_searchType=="undefined"){s_searchType="";}
if(typeof tc_vars["selected_delivery_method"]!="undefined"&&tc_vars["selected_delivery_method"]!=""){s_selectedDeliveryMethod=tc_vars["selected_delivery_method"];}else if(typeof s_selectedDeliveryMethod=="undefined"){s_selectedDeliveryMethod="";}
if(typeof tc_vars["selected_payment_method"]!="undefined"&&tc_vars["selected_payment_method"]!=""){s_selectedPaymentMethod=tc_vars["selected_payment_method"];}else if(typeof s_selectedPaymentMethod=="undefined"){s_selectedPaymentMethod="";}
if(typeof tc_vars["stock_visu_page_type"]!="undefined"&&tc_vars["stock_visu_page_type"]!=""){s_stockVisuPageType=tc_vars["stock_visu_page_type"];}else if(typeof s_stockVisuPageType=="undefined"){s_stockVisuPageType="";}
if(typeof tc_vars["stock_visu_prod_id"]!="undefined"&&tc_vars["stock_visu_prod_id"]!=""){s_stockVisuProdID=tc_vars["stock_visu_prod_id"];}else if(typeof s_stockVisuProdID=="undefined"){s_stockVisuProdID="";}
if(typeof tc_vars["stock_visu_status"]!="undefined"&&tc_vars["stock_visu_status"]!=""){s_stockVisuStatus=tc_vars["stock_visu_status"];}else if(typeof s_stockVisuStatus=="undefined"){s_stockVisuStatus="";}
if(typeof tc_vars["user_logged"]!="undefined"&&tc_vars["user_logged"]!=""){s_loginStatus=tc_vars["user_logged"];}else if(typeof s_loginStatus=="undefined"){s_loginStatus="";}
if(typeof tc_vars["user_smb"]!="undefined"&&tc_vars["user_smb"]!=""){s_accountStatus=tc_vars["user_smb"];}else if(typeof s_accountStatus=="undefined"){s_accountStatus="";}
if(typeof tc_vars["processing_fee"]!="undefined"&&tc_vars["processing_fee"]!=""){s_processingFee=tc_vars["processing_fee"];}else if(typeof s_processingFee=="undefined"){s_processingFee="";}
if(typeof tc_vars["product_shipping_fee"]!="undefined"&&tc_vars["product_shipping_fee"]!=""){s_productStdShippingFee=tc_vars["product_shipping_fee"];}else if(typeof s_productStdShippingFee=="undefined"){s_productStdShippingFee="";}
if(typeof tc_vars["shipping_fee"]!="undefined"&&tc_vars["shipping_fee"]!=""){s_shippingFee=tc_vars["shipping_fee"];}else if(typeof s_shippingFee=="undefined"){s_shippingFee="";}}
if(tC.dedup.ValidRules('109')){if(typeof tc_vars["stop_scode"]=="undefined"){tC.launchTag('109','Adobe - s_code','26','39','1');eval(tC.inclusion_s_code_1);if(typeof s!="undefined"){s.t();}}}
if(tC.dedup.ValidRules('107')){tC.launchTag('107','Google Analytics - Urchin','26','39','1');eval(tC.inclusion_urchin_1);_uacct="UA-240780-4";urchinTracker();}
if(tC.dedup.ValidRules('135')){tC.launchTag('135','Universal Analytics Standard','1503','39','1');getQueryParamA=function(p,d,u){d=d?d:"";var t=u?u.substring(u.indexOf("?")+1,u.length).split('&'):location.search.substring(1).split('&');var f=[];p=p?p.split(','):"";var g="";for(var i=0;i<t.length;i++){var x=t[i].split('=');f[x[0]]=x[1];}for(var j=0;j<p.length;j++){if(j==0){g=f[p[j]]?f[p[j]]:"";}else{g+=f[p[j]]?d+f[p[j]]:"";}}return g;};(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)})(window,document,'script','//www.google-analytics.com/analytics.js','ga');var dom_site=document.domain.replace(/www|magasins/,"")
ac_w=function(c,v,e){var c_value=escape(v)+"; path=/"+((e==null)?"":";domain="+dom_site+"; expires="+e.toUTCString());document.cookie=c+"="+c_value;}
ac_r=function(cn){var n=cn+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(n)==0)return c.substring(n.length,c.length);}return"";}
var TSFirstVisit=Number(ac_r("_gaCLT"));var TSNow=new Date().getTime();var TSExpiration=new Date();var Privacy=new Date();var myMonth=Privacy.getMonth();Privacy=new Date().setMonth(myMonth+13)
TSExpiration.setTime(Privacy);if(typeof TSFirstVisit=="undefined"||TSFirstVisit==""){TSFirstVisit=Privacy;ac_w("_gaCLT",Privacy,TSExpiration);}
var gaCLT=(TSFirstVisit-TSNow)/1000;if(typeof tc_vars["user_id"]!="undefined"&&tc_vars["user_id"]!=""){ga('create','UA-240780-16',{'cookieExpires':gaCLT,'cookieDomain':dom_site},{'userId':tc_vars["user_id"]});}else{ga('create','UA-240780-16',{'cookieExpires':gaCLT,'cookieDomain':dom_site});}
var tmp_url=document.location.pathname;var tmp_cmp=getQueryParamA('ecmp');if(tmp_cmp!=""){tmp_url+="?utm_id=";tmp_url+=tmp_cmp;}
if(typeof tc_vars["page_name"]!="undefined"&&tc_vars["page_name"]!=""){ga('set','title',tc_vars["page_name"]);}else{ga('set','title',document.title);}
if(tc_vars["template_name"]=="search:result"){tmp_url+=(tmp_url.indexOf("?")!=-1)?"&":"?";tmp_url+="int_search_k="+tc_vars["search_kw"]+"&int_search_t="
if(typeof tc_vars["search_type"]!="undefined"&&tc_vars["search_type"]!=""){tmp_url+=tc_vars["search_type"];}else{tmp_url+="internalpromotion";}
ga('set','page',tmp_url);}else{ga('set','page',tmp_url);}
if(typeof tc_vars["user_logged_status"]!="undefined"&&tc_vars["user_logged_status"]!=""){ga('set','dimension1',tc_vars["user_logged_status"]);}
if(typeof tc_vars["order_delivery_mode"]!="undefined"&&tc_vars["order_delivery_mode"]!=""){ga('set','dimension2',tc_vars["order_delivery_mode"]);}
if(typeof tc_vars["order_payment_methods"]!="undefined"&&tc_vars["order_payment_methods"]!=""){ga('set','dimension3',tc_vars["order_payment_methods"]);}
ga('send','pageview');if(typeof tc_vars["template_name"]!="undefined"){switch(tc_vars["template_name"]){case"productView":ga('require','ec');ga('ec:addProduct',{'id':tc_vars["product_id"],'name':tc_vars["product_name"],'category':tc_vars["product_category"],});ga('ec:setAction','detail');ga('send','event','Product View',tc_vars["product_category"],tc_vars["product_name"],{'nonInteraction':1});break;case"cart:fullview":ga('require','ec');if(typeof tc_vars["order_products"]!="undefined"){for(var i=0;i<tc_vars["order_products"].length;i++){ga('ec:addProduct',{'id':tc_vars["order_products"][i][0],'name':tc_vars["order_products"][i][1],'category':tc_vars["order_products"][i][7],'price':tc_vars["order_products"][i][2].replace(",","."),'quantity':tc_vars["order_products"][i][6]});}
ga('ec:setAction','checkout',{'step':1});ga('send','event','Processus de commande','Panier',{'nonInteraction':1});}
break;case"order:delivery":ga('require','ec');ga('ec:setAction','checkout',{'step':2});ga('send','event','Processus de commande','Delivery',{'nonInteraction':1});break;case"order:payment":ga('require','ec');ga('ec:setAction','checkout',{'step':3});ga('send','event','Processus de commande','Payment',{'nonInteraction':1});break;case"order:confirmation":ga('require','ec');for(var i=0;i<tc_vars["order_products"].length;i++){ga('ec:addProduct',{'id':tc_vars["order_products"][i][0],'name':tc_vars["order_products"][i][1],'category':tc_vars["order_products"][i][7],'price':tc_vars["order_products"][i][2].replace(",","."),'quantity':tc_vars["order_products"][i][6]});}
var tax=Number(tc_vars["order_amount_ati_with_sf"].replace(",","."))-Number(tc_vars["order_amount_tf_with_sf"].replace(",","."));tax=tax.toFixed(2).toString();ga('ec:setAction','purchase',{'id':tc_vars["order_id"],'revenue':tc_vars["order_amount_ati_with_sf"].replace(",","."),'tax':tax,'shipping':tc_vars["order_ship_ati"].replace(",","."),'coupon':tc_vars["order_promo_codes"],'currency':tc_vars["order_currenc"]});ga('send','event','Processus de commande','Confirmation',{'nonInteraction':1});break;}}
if(typeof tc_vars["user_nl_subscription"]!="undefined"&&tc_vars["user_nl_subscription"]!=""&&tc_vars["user_nl_subscription"]!="None"){ga('send','event','NEWSLETTER_REGISTRATION',tc_vars["user_nl_subscription"]);}}
if(tC.dedup.ValidRules('115')){if((tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Lancez vous').toLowerCase())!=-1)){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('115','NextPerf - Category','1449','39','1');(function(){var tc=document.createElement('script');tc.type='text/javascript';tc.src='//nxtck.com/act.php?tag='+'42035'+';cid='+'';(document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(tc,null);})();}}}}
if(tC.dedup.ValidRules('117')){if((tc_vars["page_name"]=='Home Page')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('117','Nextperf - Homepage tag','242','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.src="//nxtck.com/act.php?tag="+'13524';(document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);}}}}
if(tC.dedup.ValidRules('125')){if((tc_vars["page_name"]=='Process commande:Panier (Etape 1)')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('125','Criteo : OneTag basket','651','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.type="text/javascript";scriptElt1.src='//static.criteo.net/js/ld/ld.js';scriptElt1.async="true";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var criteo_q=window.criteo_q||[];window.criteo_q.push({event:"setAccount",account:'792'},{event:"setCustomerId",id:tc_vars["user_id"]},{event:"setSiteType",type:'d'},{event:"viewBasket",product:function(){var pl=[];for(var i=0;i<tc_vars["order_products"].length;++i){var product=tc_vars["order_products"][i];pl.push({id:product['0'],price:product['2'].replace(',','.').toString(),quantity:product['6']});}
return pl;},user_segment:'',ui_tcid:tc_getCookie("TCID")});if(tc_vars["order_email"]!=""){window.criteo_q.push({event:"setEmail",email:tc_vars["order_email"]});}}}}}
if(tC.dedup.ValidRules('127')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){tC.launchTag('127','Criteo : OneTag Conversion','653','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.type="text/javascript";scriptElt1.src='//static.criteo.net/js/ld/ld.js';scriptElt1.async="true";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var criteo_q=window.criteo_q||[];window.criteo_q.push({event:"setAccount",account:'792'},{event:"setCustomerId",id:tc_vars["user_id"]},{event:"setSiteType",type:'d'},{event:"trackTransaction",id:tc_vars["order_id"],new_customer:'',deduplication:'',product:function(){var pl=[];for(var i=0;i<tc_vars["order_products"].length;++i){var product=tc_vars["order_products"][i];pl.push({id:product['0'],price:product['2'],quantity:product['6']});}
return pl;},user_segment:'',ui_tcid:tc_getCookie("TCID")});if(''!=""){window.criteo_q.push({event:"setEmail",email:''});}}}}
if(tC.dedup.ValidRules('129')){if((tc_vars["page_name"]=='Home Page')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('129','Criteo : OneTag Homepage','647','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.type="text/javascript";scriptElt1.src='//static.criteo.net/js/ld/ld.js';scriptElt1.async="true";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var criteo_q=window.criteo_q||[];window.criteo_q.push({event:"setAccount",account:'792'},{event:"setCustomerId",id:tc_vars["user_id"]},{event:"setSiteType",type:'d'},{event:"viewHome",user_segment:'',ui_tcid:tc_getCookie("TCID")});if(''!=""){window.criteo_q.push({event:"setEmail",email:''});}}}}}
if(tC.dedup.ValidRules('131')){if((tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Lancez vous').toLowerCase())!=-1)){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('131','Criteo : OneTag list','649','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.type="text/javascript";scriptElt1.src='//static.criteo.net/js/ld/ld.js';scriptElt1.async="true";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var criteo_q=window.criteo_q||[];window.criteo_q.push({event:"setAccount",account:'792'},{event:"setCustomerId",id:tc_vars["user_id"]},{event:"setSiteType",type:'d'},{event:"viewList",product:function(){var pl=[];if(''.length>0){for(var i=0;i<''.length&&i<3;++i){var product=''[i];pl.push(product['']);}}
return pl;},keywords:tc_vars["search_kw"],user_segment:'',ui_tcid:tc_getCookie("TCID")});if(''!=""){window.criteo_q.push({event:"setEmail",email:''});}}}}}
if(tC.dedup.ValidRules('133')){if((tc_vars["template_name"]=='productView')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){if(tc_vars["product_delivery_time"]!='Seulement en Magasin'){tC.launchTag('133','Criteo : OneTag Product','655','39','1');var scriptElt1=document.createElement("script");scriptElt1.id="tc_script__1";scriptElt1.type="text/javascript";scriptElt1.src='//static.criteo.net/js/ld/ld.js';scriptElt1.async="true";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(scriptElt1,null);var criteo_q=window.criteo_q||[];window.criteo_q.push({event:"setAccount",account:'792'},{event:"setCustomerId",id:tc_vars["user_id"]},{event:"setSiteType",type:'d'},{event:"viewItem",product:tc_pdt_list_pdt1,user_segment:'',ui_tcid:tc_getCookie("TCID")});if(''!=""){window.criteo_q.push({event:"setEmail",email:''});}}}}}}
if(tC.dedup.ValidRules('151')){if((tc_vars["page_name"]=='Home Page')||(tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Lancez vous').toLowerCase())!=-1)||(tc_vars["template_name"]=='productView')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('151','Facebook - Custom Audience - Init (BETA)','1747','39','1');!function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,document,'script','//connect.facebook.net/en_US/fbevents.js');fbq('init','766699256788898');fbq('track','PageView');}}}}
if(tC.dedup.ValidRules('189')){if(((document.location).toString().toLowerCase().indexOf(('http://www.castorama.fr/store/pages/amenagement-mobilier-jardin_HP.html').toLowerCase())!=-1)){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('189','AdPerf conversion tag WCM','262','39','1');var adperftrackobj={client:'',amount:'',invoice_id:'',quantity:'',is_client:'',optional_parameters:{"N1":'',"N2":'',"customer_name":''},fullhost:'castorama2.solution.weborama.fr',site:'2356',conversion_page:'9'}
tC.template={};tC.template.callback=function(){adperfTracker.track(adperftrackobj)};tC.script.add("http://cstatic.weborama.fr/js/advertiserv2/adperf_conversion.js",tC.template.callback,false);}}}}
if(tC.dedup.ValidRules('191')){if(((document.location).toString().toLowerCase().indexOf(('https://www.castorama.fr/store/user/createAccount.jsp').toLowerCase())!=-1)||((document.location).toString().toLowerCase().indexOf(('https://www.castorama.fr/store/user/login.jsp').toLowerCase())!=-1)||(tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Home Page').toLowerCase())!=-1)||(tc_vars["template_name"]=='productView')||(tc_vars["page_name"]=='page pre panier'||tc_vars["page_name"]=='Process commande:Panier (Etape 1)')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('191','SaleCyle','1361','39','1');try{var __scP=(document.location.protocol=="https:")?"https://":"http://";var __scS=document.createElement("script");__scS.type="text/javascript";__scS.id="tc_script__1";__scS.async=true;__scS.src=__scP+"d16fk4ms6rqz1v.cloudfront.net/capture/"+'castorama'+".js";document.getElementsByTagName("head")[0].appendChild(__scS);}catch(e){}}}}}
if(tC.dedup.ValidRules('193')){if((tc_vars["page_name"]=='Home Page')||(tc_vars["page_name"].toString().toLowerCase().indexOf(('Catalogue:').toLowerCase())!=-1||tc_vars["page_name"].toString().toLowerCase().indexOf(('Lancez vous').toLowerCase())!=-1)||(tc_vars["template_name"]=='productView')||(tc_vars["page_name"]=='page pre panier'||tc_vars["page_name"]=='Process commande:Panier (Etape 1)')||(tc_vars["template_name"]=='order:confirmation')||(tc_vars["template_name"]=='search:result')||((document.location).toString().toLowerCase().indexOf(('https://www.castorama.fr/store/user/createAccount.jsp').toLowerCase())!=-1)||((document.location).toString().toLowerCase().indexOf(('https://www.castorama.fr/store/user/login.jsp').toLowerCase())!=-1)){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('193','Google Remarketing RLSA','26','39','1');tC.template={};tC.template.img=document.createElement("img");tC.template.img.id="tcimg_rmkt";tC.template.img.type="text/javascript";tC.template.img.src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/"+'1049680926'+"/?label="+''+"&script=0&url="+encodeURIComponent(document.location.href)+"&data=";(document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]||document.getElementsByTagName('script')[0].parentNode).insertBefore(tC.template.img,null);}}}}
if(tC.dedup.ValidRules('195')){if((tc_vars["template_name"]=='order:confirmation')){if(tC.getCookie("tc_scoring_pv")!='LP'){if(tc_browser_rules.toLowerCase().indexOf(('Internet Explorer 8').toLowerCase())===-1){tC.launchTag('195','Clic2buy','1459','39','1');var addC2BEvent=function(elem,event,listener){if(elem.attachEvent){elem.attachEvent('on'+event,listener);}else{elem.addEventListener(event,listener,false);};};var C2BTag=(function(){var c2b_c=this;c2b_c.initiate=function(ID_C2B){if(!ID_C2B){return false;}
var C2B_JSfile=document.createElement('script');var C2B_protocol=(("https:"==document.location.protocol)?"https":"http");C2B_JSfile.setAttribute("type","text/javascript");C2B_JSfile.setAttribute("src",C2B_protocol+"://assets.clic2drive.com/rts/"+ID_C2B+".js");C2B_JSfile.setAttribute("async","async");C2B_JSfile.setAttribute("defer","");if(C2B_JSfile!==undefined){document.getElementsByTagName("head")[0].appendChild(C2B_JSfile);}};return c2b_c;})();addC2BEvent(window,'load',C2BTag.initiate('d7d205'));}}}}}
function tc_events_1(tc_elt,tc_id_event,tc_array_events){tc_array_events["id"]=tc_id_event;(function(){var l='id'.split('|');for(var k in l){if(!tc_array_events.hasOwnProperty(l[k])){tc_array_events[l[k]]='';}}})();}
var tc_privacy_used=0;var tc_privacy_display_1=function(){if(tC.isCurrentVersion()){tC.script.add('//cdn.tagcommander.com/privacy/39/privacy_3.js');}}
var tc_privacy_cpt=0;function tc_privacy_wait_body_1(){if(document.body!=null){tc_privacy_display_1();}else{tc_privacy_cpt++;if(tc_privacy_cpt<20){setTimeout("tc_privacy_wait_body_1()",100);}}}
tc_privacy_wait_body_1();